In [141]:
import numpy as np
import pandas as pd
from scipy.stats import norm
import tensorflow as tf

pd.pandas.set_option('display.max_columns',None)

In [142]:
dataset = pd.read_csv('data_train3.csv')
dataset.drop(['YearRemodAdd'],axis=1,inplace=True)
dataset2 = pd.read_csv('data_train2.csv')
dataset2.drop(['YearRemodAdd'],axis=1,inplace=True)

In [143]:
dataset2.head()

,MSSubClass,MSZoning,OverallQual,RoofStyle,BsmtQual,BsmtExposure,HeatingQC,CentralAir,1stFlrSF,GrLivArea,BsmtFullBath,KitchenQual,Fireplaces,FireplaceQu,GarageType,GarageFinish,GarageCars,PavedDrive,SaleCondition
0,60,4,7,2,3,1,5,1,856,1710,1,3,0,0,5,2,2,3,5
1,20,4,6,2,3,4,5,1,1262,1262,0,2,1,3,5,2,2,3,5
2,60,4,7,2,3,3,5,1,920,1786,1,3,1,3,5,2,2,3,5
3,70,4,7,2,2,1,4,1,961,1717,1,3,1,4,2,1,3,3,2
4,60,4,8,2,3,2,5,1,1145,2198,1,3,1,3,5,2,3,3,5

In [144]:
dataset.head()

,MSSubClass,MSZoning,OverallQual,RoofStyle,BsmtQual,BsmtExposure,HeatingQC,CentralAir,1stFlrSF,GrLivArea,BsmtFullBath,KitchenQual,Fireplaces,FireplaceQu,GarageType,GarageFinish,GarageCars,PavedDrive,SaleCondition,SalePrice
0,60,4,7,2,3,1,5,1,856,1710,1,3,0,0,5,2,2,3,5,208500
1,20,4,6,2,3,4,5,1,1262,1262,0,2,1,3,5,2,2,3,5,181500
2,60,4,7,2,3,3,5,1,920,1786,1,3,1,3,5,2,2,3,5,223500
3,70,4,7,2,2,1,4,1,961,1717,1,3,1,4,2,1,3,3,2,140000
4,60,4,8,2,3,2,5,1,1145,2198,1,3,1,3,5,2,3,3,5,250000

In [145]:
dataset.columns

Index(['MSSubClass', 'MSZoning', 'OverallQual', 'RoofStyle', 'BsmtQual',
       'BsmtExposure', 'HeatingQC', 'CentralAir', '1stFlrSF', 'GrLivArea',
       'BsmtFullBath', 'KitchenQual', 'Fireplaces', 'FireplaceQu',
       'GarageType', 'GarageFinish', 'GarageCars', 'PavedDrive',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [146]:
x = dataset.iloc[:, :-1].values #take the indexes of the column/row we need to extract from dataset
y = dataset.iloc[:, -1].values
x2 = dataset2.iloc[:, :].values #take the indexes of the column/row we need to extract from dataset

In [147]:
x2

array([[60,  4,  7, ...,  2,  3,  5],
       [20,  4,  6, ...,  2,  3,  5],
       [60,  4,  7, ...,  2,  3,  5],
       ...,
       [70,  4,  7, ...,  1,  3,  5],
       [20,  4,  5, ...,  1,  3,  5],
       [20,  4,  5, ...,  1,  3,  5]], dtype=int64)

In [148]:
y

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder(),[2,4])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder(),[2,4])], remainder='passthrough')
x2 = np.array(ct.fit_transform(x2))

In [149]:
x2

array([[60,  4,  7, ...,  2,  3,  5],
       [20,  4,  6, ...,  2,  3,  5],
       [60,  4,  7, ...,  2,  3,  5],
       ...,
       [70,  4,  7, ...,  1,  3,  5],
       [20,  4,  5, ...,  1,  3,  5],
       [20,  4,  5, ...,  1,  3,  5]], dtype=int64)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder(),[44])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder(),[44])], remainder='passthrough')
x2 = np.array(ct.fit_transform(x2))

In [150]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# feature scaling

In [151]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(x_train)

MinMaxScaler()

In [152]:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [153]:
x

array([[60,  4,  7, ...,  2,  3,  5],
       [20,  4,  6, ...,  2,  3,  5],
       [60,  4,  7, ...,  2,  3,  5],
       ...,
       [70,  4,  7, ...,  1,  3,  5],
       [20,  4,  5, ...,  1,  3,  5],
       [20,  4,  5, ...,  1,  3,  5]], dtype=int64)

x = np.asarray(x).astype('float32')
y = np.asarray(y).astype('float32')
x2 = np.asarray(x2).astype('float32')

In [154]:
x_train

array([[0.        , 0.75      , 0.88888889, ..., 0.75      , 1.        ,
        1.        ],
       [0.        , 0.75      , 0.44444444, ..., 0.25      , 1.        ,
        0.8       ],
       [0.05882353, 0.75      , 0.44444444, ..., 0.5       , 1.        ,
        0.8       ],
       ...,
       [0.41176471, 0.25      , 0.55555556, ..., 0.5       , 1.        ,
        0.8       ],
       [0.58823529, 0.75      , 0.66666667, ..., 0.5       , 1.        ,
        0.8       ],
       [0.23529412, 0.75      , 0.66666667, ..., 0.5       , 1.        ,
        0.8       ]])

In [155]:
ann = tf.keras.models.Sequential()

In [156]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [157]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [158]:
ann.add(tf.keras.layers.Dense(units=1))

In [159]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

In [160]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
37/37 [==============================] - 0s 1ms/step - loss: 38848806912.0000
Epoch 2/100
37/37 [==============================] - 0s 1ms/step - loss: 38848737280.0000
Epoch 3/100
37/37 [==============================] - 0s 1ms/step - loss: 38848589824.0000
Epoch 4/100
37/37 [==============================] - 0s 1ms/step - loss: 38848237568.0000
Epoch 5/100
37/37 [==============================] - 0s 1ms/step - loss: 38847565824.0000
Epoch 6/100
37/37 [==============================] - 0s 1ms/step - loss: 38846803968.0000
Epoch 7/100
37/37 [==============================] - 0s 1ms/step - loss: 38845755392.0000
Epoch 8/100
37/37 [==============================] - 0s 844us/step - loss: 38844084224.0000
Epoch 9/100
37/37 [==============================] - 0s 1ms/step - loss: 38841610240.0000
Epoch 10/100
37/37 [==============================] - 0s 844us/step - loss: 38838476800.0000
Epoch 11/100
37/37 [==============================] - 0s 1ms/step - loss: 38834749440.0000
Epoch 12/100
37/37 [==============================] - 0s 844us/step - loss: 38830432256.0000
Epoch 13/100
37/37 [==============================] - 0s 1ms/step - loss: 38825467904.0000
Epoch 14/100
37/37 [==============================] - 0s 1ms/step - loss: 38819811328.0000
Epoch 15/100
37/37 [==============================] - 0s 2ms/step - loss: 38813462528.0000A: 0s - loss: 39573532672.000
Epoch 16/100
37/37 [==============================] - 0s 1ms/step - loss: 38806339584.0000
Epoch 17/100
37/37 [==============================] - 0s 845us/step - loss: 38798462976.0000
Epoch 18/100
37/37 [==============================] - 0s 844us/step - loss: 38789754880.0000
Epoch 19/100
37/37 [==============================] - 0s 1ms/step - loss: 38780231680.0000
Epoch 20/100
37/37 [==============================] - 0s 1ms/step - loss: 38769823744.0000
Epoch 21/100
37/37 [==============================] - 0s 1ms/step - loss: 38758502400.0000
Epoch 22/100
37/37 [==============================] - 0s 1ms/step - loss: 38746234880.0000
Epoch 23/100
37/37 [==============================] - 0s 2ms/step - loss: 38733012992.0000
Epoch 24/100
37/37 [==============================] - 0s 1ms/step - loss: 38718836736.0000
Epoch 25/100
37/37 [==============================] - 0s 1ms/step - loss: 38703689728.0000
Epoch 26/100
37/37 [==============================] - 0s 1ms/step - loss: 38687477760.0000
Epoch 27/100
37/37 [==============================] - 0s 2ms/step - loss: 38670229504.0000
Epoch 28/100
37/37 [==============================] - 0s 1ms/step - loss: 38651887616.0000
Epoch 29/100
37/37 [==============================] - 0s 1ms/step - loss: 38632534016.0000
Epoch 30/100
37/37 [==============================] - 0s 1ms/step - loss: 38612021248.0000
Epoch 31/100
37/37 [==============================] - 0s 1ms/step - loss: 38590357504.0000
Epoch 32/100
37/37 [==============================] - 0s 2ms/step - loss: 38567596032.0000
Epoch 33/100
37/37 [==============================] - 0s 1ms/step - loss: 38543630336.0000
Epoch 34/100
37/37 [==============================] - 0s 1ms/step - loss: 38518607872.0000
Epoch 35/100
37/37 [==============================] - 0s 845us/step - loss: 38492327936.0000
Epoch 36/100
37/37 [==============================] - 0s 844us/step - loss: 38464790528.0000
Epoch 37/100
37/37 [==============================] - 0s 1ms/step - loss: 38436081664.0000
Epoch 38/100
37/37 [==============================] - 0s 2ms/step - loss: 38406057984.0000
Epoch 39/100
37/37 [==============================] - 0s 1ms/step - loss: 38374977536.0000
Epoch 40/100
37/37 [==============================] - 0s 1ms/step - loss: 38342479872.0000
Epoch 41/100
37/37 [==============================] - 0s 1ms/step - loss: 38308810752.0000
Epoch 42/100
37/37 [==============================] - 0s 1ms/step - loss: 38273884160.0000
Epoch 43/100
37/37 [==============================] - 0s 1ms/step - loss: 38237446144.0000
Epoch 44/100
37/37 [==============================] - 0s 1ms/step - loss: 38199930880.0000
Epoch 45/100
37/37 [==============================] - 0s 1ms/step - loss: 38161088512.0000
Epoch 46/100
37/37 [==============================] - 0s 1ms/step - loss: 38120775680.0000
Epoch 47/100
37/37 [==============================] - 0s 1ms/step - loss: 38079303680.0000
Epoch 48/100
37/37 [==============================] - 0s 1ms/step - loss: 38036410368.0000
Epoch 49/100
37/37 [==============================] - 0s 1ms/step - loss: 37992280064.0000
Epoch 50/100
37/37 [==============================] - 0s 1ms/step - loss: 37946699776.0000
Epoch 51/100
37/37 [==============================] - 0s 1ms/step - loss: 37899759616.0000
Epoch 52/100
37/37 [==============================] - 0s 1ms/step - loss: 37851643904.0000
Epoch 53/100
37/37 [==============================] - 0s 2ms/step - loss: 37802000384.0000
Epoch 54/100
37/37 [==============================] - 0s 1ms/step - loss: 37750964224.0000
Epoch 55/100
37/37 [==============================] - 0s 1ms/step - loss: 37698482176.0000
Epoch 56/100
37/37 [==============================] - 0s 1ms/step - loss: 37644853248.0000
Epoch 57/100
37/37 [==============================] - 0s 844us/step - loss: 37589716992.0000
Epoch 58/100
37/37 [==============================] - 0s 1ms/step - loss: 37533212672.0000
Epoch 59/100
37/37 [==============================] - 0s 1ms/step - loss: 37475225600.0000
Epoch 60/100
37/37 [==============================] - 0s 1ms/step - loss: 37416140800.0000
Epoch 61/100
37/37 [==============================] - 0s 1ms/step - loss: 37355114496.0000
Epoch 62/100
37/37 [==============================] - 0s 1ms/step - loss: 37293260800.0000
Epoch 63/100
37/37 [==============================] - 0s 845us/step - loss: 37230088192.0000
Epoch 64/100
37/37 [==============================] - 0s 844us/step - loss: 37164965888.0000
Epoch 65/100
37/37 [==============================] - 0s 1ms/step - loss: 37098778624.0000
Epoch 66/100
37/37 [==============================] - 0s 1ms/step - loss: 37031428096.0000
Epoch 67/100
37/37 [==============================] - 0s 1ms/step - loss: 36962193408.0000
Epoch 68/100
37/37 [==============================] - 0s 1ms/step - loss: 36891770880.0000
Epoch 69/100
37/37 [==============================] - 0s 1ms/step - loss: 36819972096.0000
Epoch 70/100
37/37 [==============================] - 0s 844us/step - loss: 36746440704.0000
Epoch 71/100
37/37 [==============================] - 0s 1ms/step - loss: 36671614976.0000
Epoch 72/100
37/37 [==============================] - 0s 1ms/step - loss: 36595421184.0000
Epoch 73/100
37/37 [==============================] - 0s 1ms/step - loss: 36517679104.0000
Epoch 74/100
37/37 [==============================] - 0s 1ms/step - loss: 36438536192.0000
Epoch 75/100
37/37 [==============================] - 0s 1ms/step - loss: 36358021120.0000
Epoch 76/100
37/37 [==============================] - 0s 792us/step - loss: 36276580352.0000
Epoch 77/100
37/37 [==============================] - 0s 1ms/step - loss: 36192870400.0000
Epoch 78/100
37/37 [==============================] - 0s 1ms/step - loss: 36108980224.0000
Epoch 79/100
37/37 [==============================] - 0s 1ms/step - loss: 36022697984.0000
Epoch 80/100
37/37 [==============================] - 0s 1ms/step - loss: 35935559680.0000
Epoch 81/100
37/37 [==============================] - 0s 844us/step - loss: 35846696960.0000
Epoch 82/100
37/37 [==============================] - 0s 1ms/step - loss: 35756572672.0000
Epoch 83/100
37/37 [==============================] - 0s 1ms/step - loss: 35664932864.0000
Epoch 84/100
37/37 [==============================] - 0s 1ms/step - loss: 35572555776.0000
Epoch 85/100
37/37 [==============================] - 0s 1ms/step - loss: 35477946368.0000
Epoch 86/100
37/37 [==============================] - 0s 1ms/step - loss: 35382575104.0000
Epoch 87/100
37/37 [==============================] - 0s 1ms/step - loss: 35286097920.0000
Epoch 88/100
37/37 [==============================] - 0s 1ms/step - loss: 35187486720.0000
Epoch 89/100
37/37 [==============================] - 0s 1ms/step - loss: 35088355328.0000
Epoch 90/100

37/37 [==============================] - 0s 2ms/step - loss: 34987450368.0000
Epoch 91/100
37/37 [==============================] - 0s 1ms/step - loss: 34884956160.0000
Epoch 92/100
37/37 [==============================] - 0s 1ms/step - loss: 34781106176.0000
Epoch 93/100
37/37 [==============================] - 0s 2ms/step - loss: 34676363264.0000
Epoch 94/100
37/37 [==============================] - 0s 1ms/step - loss: 34569469952.0000
Epoch 95/100
37/37 [==============================] - 0s 2ms/step - loss: 34462031872.0000
Epoch 96/100
37/37 [==============================] - 0s 1ms/step - loss: 34352742400.0000
Epoch 97/100
37/37 [==============================] - 0s 2ms/step - loss: 34242684928.0000
Epoch 98/100
37/37 [==============================] - 0s 1ms/step - loss: 34131220480.0000
Epoch 99/100
37/37 [==============================] - 0s 2ms/step - loss: 34018164736.0000
Epoch 100/100
37/37 [==============================] - 0s 2ms/step - loss: 33903974400.0000

In [161]:
Y_pred = ann.predict(x_test)

In [162]:
Y_pred3 = ann.predict(x_train)

In [163]:
Y_pred2 = ann.predict(x2)

In [164]:
Y_pred2

array([[3377728.2],
       [3267396.8],
       [3561912.2],
       ...,
       [4610696.5],
       [2796093.8],
       [3240878.2]], dtype=float32)

In [165]:
Y_pred2 = Y_pred2.flatten()

In [166]:
Y_pred

array([[15082.445 ],
       [12947.535 ],
       [12504.723 ],
       [15556.427 ],
       [10075.495 ],
       [ 9323.006 ],
       [14930.51  ],
       [11214.146 ],
       [19146.943 ],
       [13343.77  ],
       [16527.799 ],
       [11184.673 ],
       [15401.246 ],
       [13048.245 ],
       [11838.527 ],
       [11876.389 ],
       [15419.336 ],
       [10274.6455],
       [11729.8545],
       [14433.389 ],
       [10471.058 ],
       [16290.217 ],
       [10451.89  ],
       [14233.178 ],
       [14340.251 ],
       [13072.588 ],
       [13434.308 ],
       [10570.167 ],
       [17848.945 ],
       [ 9657.449 ],
       [11566.325 ],
       [14941.529 ],
       [14980.239 ],
       [16295.774 ],
       [17970.174 ],
       [14797.777 ],
       [18178.502 ],
       [10831.501 ],
       [16168.025 ],
       [17009.326 ],
       [14718.569 ],
       [12395.182 ],
       [15850.393 ],
       [17485.914 ],
       [17151.254 ],
       [11228.82  ],
       [10586.565 ],
       [11469.451 ],
       [14163.209 ],
       [ 9373.93  ],
       [18812.438 ],
       [12519.934 ],
       [13436.301 ],
       [ 9705.153 ],
       [16750.836 ],
       [10880.69  ],
       [ 9856.496 ],
       [16011.291 ],
       [11004.543 ],
       [10303.072 ],
       [13872.069 ],
       [11781.007 ],
       [12356.126 ],
       [14781.381 ],
       [14920.081 ],
       [15154.307 ],
       [11591.296 ],
       [14194.505 ],
       [12735.936 ],
       [16157.198 ],
       [15793.904 ],
       [15223.488 ],
       [ 7970.209 ],
       [16082.4795],
       [10123.761 ],
       [16134.69  ],
       [12025.751 ],
       [ 8986.852 ],
       [16838.861 ],
       [14849.424 ],
       [12016.44  ],
       [11778.969 ],
       [10754.645 ],
       [11445.944 ],
       [12461.845 ],
       [14489.695 ],
       [10181.209 ],
       [15912.752 ],
       [13835.337 ],
       [11842.999 ],
       [13477.558 ],
       [15016.782 ],
       [14233.435 ],
       [14354.414 ],
       [17181.23  ],
       [13421.702 ],
       [14288.286 ],
       [13740.832 ],
       [10893.692 ],
       [11161.483 ],
       [14879.979 ],
       [14395.211 ],
       [13126.228 ],
       [12887.66  ],
       [10212.571 ],
       [15484.159 ],
       [12747.154 ],
       [ 8099.114 ],
       [15520.764 ],
       [ 9374.96  ],
       [10035.071 ],
       [12053.002 ],
       [14079.902 ],
       [13892.44  ],
       [14446.427 ],
       [14114.614 ],
       [19250.75  ],
       [11769.153 ],
       [14689.856 ],
       [16342.498 ],
       [11193.678 ],
       [12754.515 ],
       [11416.142 ],
       [14217.498 ],
       [13941.302 ],
       [17020.945 ],
       [18651.684 ],
       [15854.8125],
       [15507.867 ],
       [13244.01  ],
       [15482.956 ],
       [13999.484 ],
       [10234.184 ],
       [14991.973 ],
       [10155.761 ],
       [16556.941 ],
       [12120.268 ],
       [12620.573 ],
       [ 9995.987 ],
       [13456.951 ],
       [13095.802 ],
       [14131.339 ],
       [15192.98  ],
       [11887.908 ],
       [12071.837 ],
       [14666.059 ],
       [14715.369 ],
       [12755.657 ],
       [17906.105 ],
       [15851.222 ],
       [13758.799 ],
       [18837.336 ],
       [15229.399 ],
       [ 9959.581 ],
       [12558.526 ],
       [15602.453 ],
       [ 9849.299 ],
       [13660.152 ],
       [10334.661 ],
       [14999.332 ],
       [ 9834.336 ],
       [11543.841 ],
       [14130.599 ],
       [11043.207 ],
       [15528.116 ],
       [ 5870.383 ],
       [14779.103 ],
       [15523.763 ],
       [15774.675 ],
       [13569.462 ],
       [14530.045 ],
       [13196.7   ],
       [16209.809 ],
       [14053.967 ],
       [11441.445 ],
       [11373.302 ],
       [11469.645 ],
       [13880.274 ],
       [11212.283 ],
       [11325.709 ],
       [17536.877 ],
       [14574.26  ],
       [ 9844.216 ],
       [16363.979 ],
       [10965.409 ],
       [13825.669 ],
       [10519.806 ],
       [14343.75  ],
       [17285.49  ],
       [15571.694 ],
       [11868.229 ],
       [15010.161 ],
       [13595.09  ],
       [12179.035 ],
       [11394.395 ],
       [11811.849 ],
       [12024.066 ],
       [13366.388 ],
       [14625.929 ],
       [11982.094 ],
       [10829.596 ],
       [16835.459 ],
       [12396.841 ],
       [ 9391.056 ],
       [ 9943.087 ],
       [12679.611 ],
       [14360.273 ],
       [19481.674 ],
       [16857.21  ],
       [ 6656.319 ],
       [12067.714 ],
       [15719.543 ],
       [ 8224.261 ],
       [ 9627.6045],
       [18042.41  ],
       [12351.499 ],
       [13739.531 ],
       [16882.77  ],
       [14749.423 ],
       [10570.167 ],
       [14867.514 ],
       [14516.055 ],
       [12008.393 ],
       [12890.94  ],
       [17100.26  ],
       [16208.962 ],
       [15311.612 ],
       [15253.409 ],
       [12183.494 ],
       [13110.724 ],
       [ 8224.261 ],
       [13224.581 ],
       [ 9486.089 ],
       [12275.449 ],
       [15818.0625],
       [12071.164 ],
       [10067.045 ],
       [11131.837 ],
       [ 4665.12  ],
       [14555.267 ],
       [ 9754.664 ],
       [14901.978 ],
       [14592.253 ],
       [15934.099 ],
       [14946.764 ],
       [14151.91  ],
       [15729.218 ],
       [13575.137 ],
       [13171.127 ],
       [14660.599 ],
       [14526.668 ],
       [16574.547 ],
       [ 9337.68  ],
       [19064.248 ],
       [15168.392 ],
       [16184.68  ],
       [ 9153.857 ],
       [16373.18  ],
       [19278.182 ],
       [22868.855 ],
       [14993.699 ],
       [12330.804 ],
       [10050.222 ],
       [ 6664.1245],
       [18824.436 ],
       [18559.744 ],
       [18639.898 ],
       [ 7139.0986],
       [14982.386 ],
       [14469.759 ],
       [10355.932 ],
       [14286.7295],
       [10057.34  ],
       [13208.069 ],
       [ 9205.723 ],
       [14435.373 ],
       [12964.261 ],
       [13548.708 ],
       [15790.009 ],
       [ 9506.395 ],
       [10731.9375],
       [18360.96  ],
       [12738.571 ],
       [12841.042 ],
       [15428.123 ],
       [10557.89  ],
       [10988.513 ],
       [18667.572 ],
       [19850.701 ],
       [10789.074 ],
       [ 9161.8125],
       [ 6898.7173]], dtype=float32)

In [167]:
y_test

array([200624, 133000, 110000, 192000,  88000,  85000, 282922, 141000,
       745000, 148800, 208900, 136905, 225000, 123000, 119200, 145000,
       190000, 123600, 149350, 155000, 166000, 144500, 110000, 174000,
       185000, 168000, 177500,  84500, 320000, 118500, 110000, 213000,
       156000, 250000, 372500, 175000, 277500, 112500, 263000, 325000,
       243000, 130000, 164990, 280000, 403000, 119000, 125000, 128200,
       172500,  84900, 412500, 156000, 167900, 100000, 275000, 123000,
       132000, 239900, 139000, 115000, 137500, 135000, 134450, 180500,
       193500, 156500, 132000, 224500, 139000, 225000, 188500, 118000,
        82000, 392000, 112000, 248900, 134500,  79500, 320000, 158000,
       140000, 136500, 107500, 145000, 200500, 185000, 105000, 202665,
       186000, 136000, 200500, 190000, 187500, 200000, 172500, 157000,
       213000, 185000, 124500, 162900, 260000, 198500, 120000, 159500,
       105900, 260000, 143000, 106500, 178900, 127000,  90350, 118500,
       190000, 119900, 183900, 155000, 386250, 133000, 193500, 270000,
       141000, 146000, 128500, 176000, 214000, 222000, 415298, 187750,
       199900, 180000, 206300, 194000, 142953, 182900, 116050, 213250,
       139500, 179000, 107900, 175900, 158500, 145000, 217000, 150500,
       108959, 165600, 201000, 145500, 319900, 215000, 180500, 367294,
       239000, 145900, 161000, 250000,  89471, 230000, 147000, 163900,
        97000, 142000, 197000, 129000, 232000, 115000, 175000, 265000,
       207000, 181000, 176000, 171000, 196000, 176000, 113000, 139000,
       135000, 240000, 112000, 134000, 316600, 170000, 116000, 306000,
        82500, 175000, 106000, 194000, 194201, 155900, 138000, 177000,
       214000, 148000, 127000, 142500,  80000, 145000, 171000, 122500,
       139000, 189000, 120500, 124000, 160000, 200000, 160000, 313000,
       275000,  67000, 159000, 251000,  92900, 109500, 385000, 129000,
        82500, 301000, 249700,  81000, 187500, 110000, 117000, 128500,
       213490, 284000, 230500, 190000, 135000, 152000,  87500, 155000,
       115000, 144000, 248000, 132500, 136000, 117000,  82000, 157500,
       110000, 181000, 192500, 223500, 181500, 170000, 187500, 185900,
       160000, 192000, 181900, 266000,  99900, 438780, 229456, 216837,
       110500, 175900, 538000, 160000, 172500, 108000, 131500, 106250,
       385000, 370878, 345000,  68500, 250000, 245350, 125000, 234000,
       145000, 181000, 104000, 233000, 164000, 219500, 195000, 108000,
       149900, 315000, 177500, 140000, 193879, 137900, 118000, 324000,
       555000, 136000,  82500, 101000], dtype=int64)

In [168]:
y_train

array([314813, 109500, 163500, ..., 112000, 234000, 221000], dtype=int64)

In [169]:
y_test

array([200624, 133000, 110000, 192000,  88000,  85000, 282922, 141000,
       745000, 148800, 208900, 136905, 225000, 123000, 119200, 145000,
       190000, 123600, 149350, 155000, 166000, 144500, 110000, 174000,
       185000, 168000, 177500,  84500, 320000, 118500, 110000, 213000,
       156000, 250000, 372500, 175000, 277500, 112500, 263000, 325000,
       243000, 130000, 164990, 280000, 403000, 119000, 125000, 128200,
       172500,  84900, 412500, 156000, 167900, 100000, 275000, 123000,
       132000, 239900, 139000, 115000, 137500, 135000, 134450, 180500,
       193500, 156500, 132000, 224500, 139000, 225000, 188500, 118000,
        82000, 392000, 112000, 248900, 134500,  79500, 320000, 158000,
       140000, 136500, 107500, 145000, 200500, 185000, 105000, 202665,
       186000, 136000, 200500, 190000, 187500, 200000, 172500, 157000,
       213000, 185000, 124500, 162900, 260000, 198500, 120000, 159500,
       105900, 260000, 143000, 106500, 178900, 127000,  90350, 118500,
       190000, 119900, 183900, 155000, 386250, 133000, 193500, 270000,
       141000, 146000, 128500, 176000, 214000, 222000, 415298, 187750,
       199900, 180000, 206300, 194000, 142953, 182900, 116050, 213250,
       139500, 179000, 107900, 175900, 158500, 145000, 217000, 150500,
       108959, 165600, 201000, 145500, 319900, 215000, 180500, 367294,
       239000, 145900, 161000, 250000,  89471, 230000, 147000, 163900,
        97000, 142000, 197000, 129000, 232000, 115000, 175000, 265000,
       207000, 181000, 176000, 171000, 196000, 176000, 113000, 139000,
       135000, 240000, 112000, 134000, 316600, 170000, 116000, 306000,
        82500, 175000, 106000, 194000, 194201, 155900, 138000, 177000,
       214000, 148000, 127000, 142500,  80000, 145000, 171000, 122500,
       139000, 189000, 120500, 124000, 160000, 200000, 160000, 313000,
       275000,  67000, 159000, 251000,  92900, 109500, 385000, 129000,
        82500, 301000, 249700,  81000, 187500, 110000, 117000, 128500,
       213490, 284000, 230500, 190000, 135000, 152000,  87500, 155000,
       115000, 144000, 248000, 132500, 136000, 117000,  82000, 157500,
       110000, 181000, 192500, 223500, 181500, 170000, 187500, 185900,
       160000, 192000, 181900, 266000,  99900, 438780, 229456, 216837,
       110500, 175900, 538000, 160000, 172500, 108000, 131500, 106250,
       385000, 370878, 345000,  68500, 250000, 245350, 125000, 234000,
       145000, 181000, 104000, 233000, 164000, 219500, 195000, 108000,
       149900, 315000, 177500, 140000, 193879, 137900, 118000, 324000,
       555000, 136000,  82500, 101000], dtype=int64)

In [170]:
import csv
with open('export3.csv','w',newline='') as csvfile:
    fieldnames=['Id','SalePrice']
    thewriter=csv.DictWriter(csvfile,fieldnames=fieldnames)
    thewriter.writeheader() 
    count = 1460
    for i in range(len(Y_pred2)):
        count += 1
        thewriter.writerow({'Id':count, 'SalePrice':Y_pred2[i]})